# Generated by Django 2.2.1 on 2019-11-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Enter participant first name.', max_length=20, null=True)),
                ('last_name', models.CharField(help_text='Enter participant last name.', max_length=20, null=True)),
                ('siblings', models.CharField(help_text='Participant has siblings.', max_length=20, null=True)),
                ('environmental_exposures', models.CharField(help_text='Genetic Mutations', max_length=20, null=True)),
                ('genetic_mutations', models.CharField(help_text='Genetic Mutations', max_length=20, null=True)),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
    ]
